In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('medical_insurance.csv')

df.head(5) # this is very similar to select top 2 * from df

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,...,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,...,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,...,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,...,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,...,0,1,0,2,0,1,1,0,1,0

In [5]:
df.columns

Index(['person_id', 'age', 'sex', 'region', 'urban_rural', 'income',
       'education', 'marital_status', 'employment_status', 'household_size',
       'dependents', 'bmi', 'smoker', 'alcohol_freq', 'visits_last_year',
       'hospitalizations_last_3yrs', 'days_hospitalized_last_3yrs',
       'medication_count', 'systolic_bp', 'diastolic_bp', 'ldl', 'hba1c',
       'plan_type', 'network_tier', 'deductible', 'copay', 'policy_term_years',
       'policy_changes_last_2yrs', 'provider_quality', 'risk_score',
       'annual_medical_cost', 'annual_premium', 'monthly_premium',
       'claims_count', 'avg_claim_amount', 'total_claims_paid',
       'chronic_count', 'hypertension', 'diabetes', 'asthma', 'copd',
       'cardiovascular_disease', 'cancer_history', 'kidney_disease',
       'liver_disease', 'arthritis', 'mental_health', 'proc_imaging_count',
       'proc_surgery_count', 'proc_physio_count', 'proc_consult_count',
       'proc_lab_count', 'is_high_risk', 'had_major_procedure'],
      dtype='object')

In [6]:
df.columns


# lets say you want to see the first 10 rows of specific columns
df[['age', 'bmi', 'income']].head(10)  # this is similar to select age, bmi, charges from df limit 10

   age   bmi    income
0   52  27.4   22700.0
1   79  26.6   12800.0
2   68  31.5   40700.0
3   15  31.6   15600.0
4   53  30.5   89600.0
5   63  20.4  305000.0
6   36  21.6   38900.0
7   21  30.7   83700.0
8   53  27.8   60700.0
9   28  31.0   23600.0

In [8]:
df[['urban_rural','smoker']].head(10)  # this is similar to select urban_rural, smoker from df limit 10

  urban_rural   smoker
0    Suburban    Never
1       Urban    Never
2       Rural    Never
3    Suburban    Never
4    Suburban    Never
5       Rural    Never
6       Rural    Never
7    Suburban    Never
8    Suburban  Current
9       Urban    Never

In [10]:
df.shape

(100000, 54)

In [11]:
df.columns

Index(['person_id', 'age', 'sex', 'region', 'urban_rural', 'income',
       'education', 'marital_status', 'employment_status', 'household_size',
       'dependents', 'bmi', 'smoker', 'alcohol_freq', 'visits_last_year',
       'hospitalizations_last_3yrs', 'days_hospitalized_last_3yrs',
       'medication_count', 'systolic_bp', 'diastolic_bp', 'ldl', 'hba1c',
       'plan_type', 'network_tier', 'deductible', 'copay', 'policy_term_years',
       'policy_changes_last_2yrs', 'provider_quality', 'risk_score',
       'annual_medical_cost', 'annual_premium', 'monthly_premium',
       'claims_count', 'avg_claim_amount', 'total_claims_paid',
       'chronic_count', 'hypertension', 'diabetes', 'asthma', 'copd',
       'cardiovascular_disease', 'cancer_history', 'kidney_disease',
       'liver_disease', 'arthritis', 'mental_health', 'proc_imaging_count',
       'proc_surgery_count', 'proc_physio_count', 'proc_consult_count',
       'proc_lab_count', 'is_high_risk', 'had_major_procedure'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 54 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   sex                          100000 non-null  object
 3   region                       100000 non-null  object
 4   urban_rural                  100000 non-null  object
 5   income                       100000 non-null  float64
 6   education                    100000 non-null  object
 7   marital_status               100000 non-null  object
 8   employment_status            100000 non-null  object
 9   household_size               100000 non-null  int64
 10  dependents                   100000 non-null  int64
 11  bmi                          100000 non-null  float64
 12  smoker                       100000 non-null  object
 13  alcohol_freq                 69917 non-null   object
 14  visits_last_year             100000 non-null  int64
 15  hospitalizations_last_3yrs   100000 non-null  int64
 16  days_hospitalized_last_3yrs  100000 non-null  int64
 17  medication_count             100000 non-null  int64
 18  systolic_bp                  100000 non-null  float64
 19  diastolic_bp                 100000 non-null  float64
 20  ldl                          100000 non-null  float64
 21  hba1c                        100000 non-null  float64
 22  plan_type                    100000 non-null  object
 23  network_tier                 100000 non-null  object
 24  deductible                   100000 non-null  int64
 25  copay                        100000 non-null  int64
 26  policy_term_years            100000 non-null  int64
 27  policy_changes_last_2yrs     100000 non-null  int64
 28  provider_quality             100000 non-null  float64
 29  risk_score                   100000 non-null  float64
 30  annual_medical_cost          100000 non-null  float64
 31  annual_premium               100000 non-null  float64
 32  monthly_premium              100000 non-null  float64
 33  claims_count                 100000 non-null  int64
 34  avg_claim_amount             100000 non-null  float64
 35  total_claims_paid            100000 non-null  float64
 36  chronic_count                100000 non-null  int64
 37  hypertension                 100000 non-null  int64
 38  diabetes                     100000 non-null  int64
 39  asthma                       100000 non-null  int64
 40  copd                         100000 non-null  int64
 41  cardiovascular_disease       100000 non-null  int64
 42  cancer_history               100000 non-null  int64
 43  kidney_disease               100000 non-null  int64
 44  liver_disease                100000 non-null  int64
 45  arthritis                    100000 non-null  int64
 46  mental_health                100000 non-null  int64
 47  proc_imaging_count           100000 non-null  int64
 48  proc_surgery_count           100000 non-null  int64
 49  proc_physio_count            100000 non-null  int64
 50  proc_consult_count           100000 non-null  int64
 51  proc_lab_count               100000 non-null  int64
 52  is_high_risk                 100000 non-null  int64
 53  had_major_procedure          100000 non-null  int64
dtypes: float64(13), int64(31), object(10)
memory usage: 41.2+ MB

In [7]:
type(df['age'])  # this will give you the data type of the series object

pandas.core.series.Series

In [16]:
df.smoker.value_counts()

smoker
Never      69709
Former     18163
Current    12128
Name: count, dtype: int64

In [17]:
# excel : you do filtering 
condition = df['age'] > 20
condition_2 = df['smoker'] == 'Current'
df[condition & condition_2].head(10)

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
8,60768,53,Male,North,Suburban,60700.0,No HS,Divorced,Retired,1,...,0,0,0,0,0,1,0,1,1,0
14,20425,63,Male,South,Urban,100700.0,Bachelors,Single,Unemployed,1,...,0,0,0,0,0,1,0,0,1,0
17,1762,59,Male,East,Urban,61900.0,Masters,Married,Employed,2,...,0,0,1,0,2,0,1,1,1,1
26,88637,43,Female,East,Urban,15400.0,Bachelors,Single,Employed,1,...,0,0,0,1,0,1,1,1,1,0
40,19793,64,Male,East,Suburban,6800.0,Bachelors,Widowed,Employed,3,...,0,0,1,0,0,0,0,0,1,0
42,40164,84,Female,North,Urban,26500.0,Bachelors,Married,Retired,2,...,0,0,0,0,0,0,0,0,1,0
87,87071,31,Male,Central,Urban,27800.0,Masters,Married,Employed,2,...,0,0,0,2,0,0,1,0,0,1
90,49183,34,Male,West,Suburban,148600.0,Some College,Married,Employed,4,...,0,0,0,0,0,1,1,0,0,0
96,81347,79,Male,Central,Rural,68200.0,HS,Married,Employed,2,...,0,0,0,0,0,1,0,0,1,0
114,73646,59,Male,West,Urban,19600.0,Bachelors,Married,Self-employed,2,...,0,0,0,0,0,1,1,2,1,0

In [20]:
# lets do more filtering example
df[(df['age'] > 30) & (df['bmi'] > 25) & (df['income'] > 20000)][['age', 'bmi', 'income']].head(10)

    age   bmi    income
0    52  27.4   22700.0
2    68  31.5   40700.0
4    53  30.5   89600.0
8    53  27.8   60700.0
12   50  33.4   43100.0
14   63  31.3  100700.0
15   52  30.0   31900.0
19   53  32.1   41300.0
20   54  25.5   76400.0
21   61  30.0  211200.0

In [28]:
condition_1 = (df['age'] > 30) & (df['bmi'] > 25)
condition_2 = (df['income'] > 20000)
df_income =df[condition_1 & condition_2]
df_income[['age', 'bmi', 'income']].head(10)

    age   bmi    income
0    52  27.4   22700.0
2    68  31.5   40700.0
4    53  30.5   89600.0
8    53  27.8   60700.0
12   50  33.4   43100.0
14   63  31.3  100700.0
15   52  30.0   31900.0
19   53  32.1   41300.0
20   54  25.5   76400.0
21   61  30.0  211200.0

In [32]:
df.age.mean() # average age of the people in the dataset
df.bmi.mean() # average bmi of the people in the dataset
df.income.mean() # average income of the people in the dataset


# different attributes and methods
df.age.min()  # minimum age
df.age.max()  # maximum age
df.age.std()  # standard deviation of age
df.age.describe()  # this will give you count, mean, std, min, 25%, 50%, 75%, max

count    100000.000000
mean         47.521500
std          15.988752
min           0.000000
25%          37.000000
50%          48.000000
75%          58.000000
max         100.000000
Name: age, dtype: float64

In [38]:
df[['income', 'age','sex']].describe(include='all')  # this will give you count, mean, std, min, 25%, 50%, 75%, max for income and charges columns

              income            age     sex
count   1.000000e+05  100000.000000  100000
unique           NaN            NaN       3
top              NaN            NaN  Female
freq             NaN            NaN   49193
mean    4.987390e+04      47.521500     NaN
std     4.680021e+04      15.988752     NaN
min     1.100000e+03       0.000000     NaN
25%     2.110000e+04      37.000000     NaN
50%     3.620000e+04      48.000000     NaN
75%     6.220000e+04      58.000000     NaN
max     1.061800e+06     100.000000     NaN

In [39]:
df.sex.value_counts()

sex
Female    49193
Male      48794
Other      2013
Name: count, dtype: int64

In [41]:
# how to create data frames from scratch
import numpy as np
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [24, 30, np.nan, 35],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

custom_df = pd.DataFrame(data)
custom_df.head()

      name   age         city
0    Alice  24.0     New York
1      Bob  30.0  Los Angeles
2  Charlie   NaN      Chicago
3    David  35.0      Houston

In [42]:
# 
custom_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     3 non-null      float64
 2   city    4 non-null      object
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes

In [44]:
custom_df.isnull().sum()

name    0
age     1
city    0
dtype: int64

In [ ]:
df.isnull().sum()  # this will give you the count of null values in each column

person_id                          0
age                                0
sex                                0
region                             0
urban_rural                        0
income                             0
education                          0
marital_status                     0
employment_status                  0
household_size                     0
dependents                         0
bmi                                0
smoker                             0
alcohol_freq                   30083
visits_last_year                   0
hospitalizations_last_3yrs         0
days_hospitalized_last_3yrs        0
medication_count                   0
systolic_bp                        0
diastolic_bp                       0
ldl                                0
hba1c                              0
plan_type                          0
network_tier                       0
deductible                         0
copay                              0
policy_term_years                  0
policy_changes_last_2yrs           0
provider_quality                   0
risk_score                         0
annual_medical_cost                0
annual_premium                     0
monthly_premium                    0
claims_count                       0
avg_claim_amount                   0
total_claims_paid                  0
chronic_count                      0
hypertension                       0
diabetes                           0
asthma                             0
copd                               0
cardiovascular_disease             0
cancer_history                     0
kidney_disease                     0
liver_disease                      0
arthritis                          0
mental_health                      0
proc_imaging_count                 0
proc_surgery_count                 0
proc_physio_count                  0
proc_consult_count                 0
proc_lab_count                     0
is_high_risk                       0
had_major_procedure                0
dtype: int64

In [48]:
needto_preport = df[df.isnull().any(axis=1)][['alcohol_freq','age']] # this will give you all the rows which have null values in any column

In [50]:
needto_preport.to_csv('need_to_report.csv', index=False)

In [ ]:
# Assignment: Explore more on pandas documentation and try to find out more methods and attributes of pandas data frame and series objects.

# lets say you below columns
df.columns 

# ['person_id', 'age', 'sex', 'region', 'urban_rural', 'income',
#        'education', 'marital_status', 'employment_status', 'household_size',
#        'dependents', 'bmi', 'smoker', 'alcohol_freq', 'visits_last_year',
#        'hospitalizations_last_3yrs', 'days_hospitalized_last_3yrs',
#        'medication_count', 'systolic_bp', 'diastolic_bp', 'ldl', 'hba1c',
#        'plan_type', 'network_tier', 'deductible', 'copay', 'policy_term_years',
#        'policy_changes_last_2yrs', 'provider_quality', 'risk_score',
#        'annual_medical_cost', 'annual_premium', 'monthly_premium',
#        'claims_count', 'avg_claim_amount', 'total_claims_paid',
#        'chronic_count', 'hypertension', 'diabetes', 'asthma', 'copd',
#        'cardiovascular_disease', 'cancer_history', 'kidney_disease',
#        'liver_disease', 'arthritis', 'mental_health', 'proc_imaging_count',
#        'proc_surgery_count', 'proc_physio_count', 'proc_consult_count',
#        'proc_lab_count', 'is_high_risk', 'had_major_procedure']


# Q1) Find out average, min, max, std deviation of 'annual_medical_cost' and 'annual_premium' columns.
# Q2) Find out how many unique values are there in 'region', 'education', 'plan_type' columns. # use value_counts() or nunique()
# Q3) Find out the count of each unique value in 'employment_status' and 'marital_status' columns.
# Q4) Find out how many people have 'diabetes' and 'hypertension' in the dataset.
# Q5) Find out the average 'bmi' of people who are 'Current' smokers.
# Q6) Find out how many people have 'is_high_risk' as True and had 'had_major_procedure' as True.
# Q7) Find out the correlation between 'age', 'bmi', 'income', 'annual_medical_cost', 'annual_premium' columns.
# Q8) Create a new column 'cost_to_premium_ratio' which is the ratio of 'annual_medical_cost' to 'annual_premium'.
# Q9) Find out the top 5 people who have the highest 'risk_score' in the dataset.
# Q10) Find out how many people have 'chronic_count' greater than

Index(['person_id', 'age', 'sex', 'region', 'urban_rural', 'income',
       'education', 'marital_status', 'employment_status', 'household_size',
       'dependents', 'bmi', 'smoker', 'alcohol_freq', 'visits_last_year',
       'hospitalizations_last_3yrs', 'days_hospitalized_last_3yrs',
       'medication_count', 'systolic_bp', 'diastolic_bp', 'ldl', 'hba1c',
       'plan_type', 'network_tier', 'deductible', 'copay', 'policy_term_years',
       'policy_changes_last_2yrs', 'provider_quality', 'risk_score',
       'annual_medical_cost', 'annual_premium', 'monthly_premium',
       'claims_count', 'avg_claim_amount', 'total_claims_paid',
       'chronic_count', 'hypertension', 'diabetes', 'asthma', 'copd',
       'cardiovascular_disease', 'cancer_history', 'kidney_disease',
       'liver_disease', 'arthritis', 'mental_health', 'proc_imaging_count',
       'proc_surgery_count', 'proc_physio_count', 'proc_consult_count',
       'proc_lab_count', 'is_high_risk', 'had_major_procedure'],
      dtype='object')

In [55]:
# Q1) Find out average, min, max, std deviation of 'annual_medical_cost' and 'annual_premium' columns.

def basic_stats(column_name):
    avg = df[column_name].mean()
    min_val = df[column_name].min()
    max_val = df[column_name].max()
    std_dev = df[column_name].std()
    return {
        'average': avg,
        'min': min_val,
        'max': max_val,
        'std_deviation': std_dev
    }

# Q1) Find out average, min, max, std deviation of 'annual_medical_cost' and 'annual_premium' columns.
annual_medical_cost_stats = basic_stats('annual_medical_cost')
annual_premium_stats = basic_stats('annual_premium')
print("Annual Medical Cost Stats:", annual_medical_cost_stats)
print("Annual Premium Stats:", annual_premium_stats)

Annual Medical Cost Stats: {'average': np.float64(3009.4519069999997), 'min': np.float64(55.55), 'max': np.float64(65724.9), 'std_deviation': np.float64(3127.4628223865643)}
Annual Premium Stats: {'average': np.float64(582.3200396999999), 'min': np.float64(211.67), 'max': np.float64(10962.55), 'std_deviation': np.float64(399.58372199751363)}

In [57]:
df.region.value_counts()

region
South      28029
North      22027
East       19984
West       17879
Central    12081
Name: count, dtype: int64

In [ ]:
# https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented