In [1]:
import pandas as pd

data = {
    "product_category": ["Electronics", "Clothing", "Groceries", "Electronics", "Clothing"],
    "sales_amount": [1200, 800, 150, 3000, 600],
}

df = pd.DataFrame(data)

df.head()

  product_category  sales_amount
0      Electronics          1200
1         Clothing           800
2        Groceries           150
3      Electronics          3000
4         Clothing           600

In [3]:
df.groupby("product_category").agg({"sales_amount": ["sum", "mean", "max"]})

                 sales_amount
                          sum    mean   max
product_category
Clothing                 1400   700.0   800
Electronics              4200  2100.0  3000
Groceries                 150   150.0   150

In [4]:
# You can pass more then two columns also for group by 

data = {
    "product_category": ["Electronics", "Clothing", "Groceries", "Electronics", "Clothing", "Groceries"],
    "region": ["North", "South", "East", "West", "North", "South"],
    "sales_amount": [1200, 800, 150, 3000, 600, 400],
}

df = pd.DataFrame(data)

df.head()

  product_category region  sales_amount
0      Electronics  North          1200
1         Clothing  South           800
2        Groceries   East           150
3      Electronics   West          3000
4         Clothing  North           600

In [5]:
df.groupby(["region", "product_category"]).agg({"sales_amount": ["sum", "mean", "max"]})
# this is very similar to sql group by operation 
# select region, product_category, sum(sales_amount), avg(sales_amount), max(sales_amount) from table group by region, product_category
# you can also compare it with excel pivot table operation

                        sales_amount
                                 sum    mean   max
region product_category
East   Groceries                 150   150.0   150
North  Clothing                  600   600.0   600
       Electronics              1200  1200.0  1200
South  Clothing                  800   800.0   800
       Groceries                 400   400.0   400
West   Electronics              3000  3000.0  3000

In [8]:
sales_report = df.groupby(["region", "product_category"]).agg({"sales_amount": ["sum", "mean", "max"]})
sales_report.to_excel("sales_report.xlsx")  # Exporting the report to an Excel file

In [7]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [13]:
# sometime we need to join different dataframe to get the desired result. For example, we have two dataframes, one with product details and another with sales details. We can join them based on a common column like 'product_id' to get a comprehensive view of sales by product category.
product_data = {
    "product_id": [1, 2, 3],
    "product_category": ["Electronics", "Clothing", "Groceries"],
}
sales_data = {
    "product_id": [1, 2, 1, 3, 8],
    "sales_amount": [1200, 800, 3000, 150, 600],
}

df_products = pd.DataFrame(product_data)
df_sales = pd.DataFrame(sales_data)

In [14]:
df_products.head()

   product_id product_category
0           1      Electronics
1           2         Clothing
2           3        Groceries

In [15]:
df_sales.head()

   product_id  sales_amount
0           1          1200
1           2           800
2           1          3000
3           3           150
4           8           600

In [20]:
#lets join : left join
amount = pd.merge(df_sales, df_products, on="product_id", how="left")

In [23]:
# lets create one more dataframe where product_id , region and profit_margin is given
region_data = {
    "product_id": [1, 2, 3],
    "region": ["North", "South", "East"],
    "profit_margin": [0.2, 0.15, 0.1],
}
df_regions = pd.DataFrame(region_data)

In [25]:
final_df = pd.merge(amount, df_regions, on="product_id", how="left")

In [27]:
final_df.head(2)

# lets create more coumns based on existing columns
final_df["total_profit"] = final_df["sales_amount"] * final_df["profit_margin"]
final_df.head(2)

,product_id,sales_amount,product_category,region,profit_margin,total_profit
0,1,1200,Electronics,North,0.20,240.0
1,2,800,Clothing,South,0.15,120.0

## Reference 
- https://www.quora.com/What-are-Joins-in-SQL-and-their-importance